### ISSUE TITLE
pi4j-example-minimal doesn't work on Raspberry Pi 5

### ISSUE THREAD

**Issue by SergeySn** [Pi4J/pi4j#320]
I am trying to run pi4j-example-minimal as is on Raspberry Pi 5.  It compiles fine.  But when I try to run it I get this error:
**[main] WARN com.pi4j.library.pigpio.impl.PiGpioNativeImpl - PIGPIO ERROR: PI_INIT_FAILED; pigpio initialisation failed
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException**
What might be the problem?

P.S.  I am using:
Java openjdk version "11.0.21" 2023-10-17 LTS
Apache Maven 3.8.7
Linux pi 6.1.0-rpi7-rpi-2712 1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux
Full log is here: [error.txt](https://github.com/Pi4J/pi4j-v2/files/14150108/error.txt)
Any help is greatly appreciated.
Thanks a lot 
Sergey

**Comment by FDelporte** [comment]
Indeed, Pi4J is not yet compatible with RPi5, see #321
