### ISSUE TITLE
Merge pi4j-board-info into core library

### ISSUE THREAD

**Issue by FDelporte** [Pi4J/pi4j#340]
To allow the easy detection of the Raspberry Pi board so plugins can define their priority and other settings, e.g. PWM address, based on the type of board.

Merge https://github.com/Pi4J/pi4j-board-info into this project

**Comment by eitch** [comment]
@FDelporte I think this issue can be closed, right?

**Comment by FDelporte** [comment]
correct @eitch , thanks for the cleanup ;-)
