### ISSUE TITLE
what is the differenct bwtween pi4j and pi4j-v2

### ISSUE THREAD

**Issue by 897180673** [Pi4J/pi4j#35]

**Comment by FDelporte** [comment]
V1 uses WiringPi as the underlying framework to handle the GPIO, but this got obsolete last year. We plan to make some final releases of this V1 to have support for Java 8 and Raspberry Pi 4.
V2 uses PiGpio for the GPIO, uses Java 11, is fully modular, and focuses on the core-functionality, not specific hardware devices. The documentation site of V2 is work-in-progress and available on https://v2.pi4j.com/
