### ISSUE TITLE
Unexpected  PI_BAD_HANDLE

### ISSUE THREAD

**Issue by SSNC-SushilBohaju** [Pi4J/pi4j#360]
When i close the program, I got the strange error code :  PIGPIO ERROR: PI_BAD_HANDLE; unknown handle
Does anyone know the error on pi4j V2.

**Comment by taartspi** [comment]
To try and help more information is needed.  Please provide more details. Pi model, SNAPSHOT used, java version, and the stack trace.   With those someone may have insight to the cause of your exception.

**Comment by SSNC-SushilBohaju** [comment]
![image](https://github.com/Pi4J/pi4j-v2/assets/112843183/0da1bdc8-689c-4f5f-9aa5-65e4a864b5a1)
[Uploading hs_err_pid1565.log…]()

**Comment by SSNC-SushilBohaju** [comment]
> To try and help more information is needed. Please provide more details. Pi model, SNAPSHOT used, java version, and the stack trace. With those someone may have insight to the cause of your exception.

[Err_SnsrCtlApp_20240521.log](https://github.com/Pi4J/pi4j-v2/files/15396486/Err_SnsrCtlApp_20240521.log)

**Comment by taartspi** [comment]
1. Are you using Remote Pigpio to execute your code, does the entire program execute on your Pi4 
2. Did the program function correctly until you tried to close the program 
3. Looks like the upload hs_err_pid1565.log was not successful
4. line 1081 shows the pi4j context is already shutdown, which makes sense as you said you closed the program. But the next line 'getGridFeedInOutPowerModbus' implies you still have some portion of the program functioning(maybe a separate thread) .  Is there code still running and it is creating these error messages ?

**Comment by taartspi** [comment]
And the error message, most if not all Pigpio I2C  functions can return this Error_Code. Something as simple as you closed the device by it going out of scope,  and then attempted to read or write from the same  device, using a stale handle

**Comment by SSNC-SushilBohaju** [comment]
> 1. Are you using Remote Pigpio to execute your code, does the entire program execute on your Pi4
> 2. Did the program function correctly until you tried to close the program
> 3. Looks like the upload hs_err_pid1565.log was not successful
> 4. line 1081 shows the pi4j context is already shutdown, which makes sense as you said you closed the program. But the next line 'getGridFeedInOutPowerModbus' implies you still have some portion of the program functioning(maybe a separate thread) .  Is there code still running and it is creating these error messages ?

All program running inside rpi
When i close program using cltr+c
![image](https://github.com/Pi4J/pi4j-v2/assets/112843183/09e064d0-a3c6-4a77-9a85-afe53d4360a4)
After 1081 line the following logs are generate after re execute the program you can check with time frame
Its just a warning but it make my err log difficult for read so i am looking from where this warn log are printing

**Comment by taartspi** [comment]
that NOT INITIALIZED error, if you program was successfully reading from your I2C device  prior to ctrlC I again ask if you have some thread still running after you ctrlC your program. At any rate. The logs yesterday look like some code is repeatedly accessing an I2C device, so I think you need to just use the debugger, set a break point for any of your I2C calls and make sure they are working and see when they begin to fail.

**Comment by SSNC-SushilBohaju** [comment]
> that NOT INITIALIZED error, if you program was successfully reading from your I2C device prior to ctrlC I again ask if you have some thread still running after you ctrlC your program. At any rate. The logs yesterday look like some code is repeatedly accessing an I2C device, so I think you need to just use the debugger, set a break point for any of your I2C calls and make sure they are working and see when they begin to fail.

Thank you for your help .... problem is solved. :)

**Comment by taartspi** [comment]
Glad you solved it.  Tom
