### ISSUE TITLE
Unable to detect board type

### ISSUE THREAD

**Issue by byRizon** [Pi4J/pi4j#421]
BoardInfoHelper.class is unable to detect my RaspberryPi 5 board type due to error:
`Could not execute cat /proc/cpuinfo | grep 'Revision' | awk '{print $3}' to detect the board model: IOException: Cannot run program "sh": error=13, Permission denied`

The .jar file is executed by the root user.
Is there a workaround for the error?

**Comment by FDelporte** [comment]
auch, that is strange

do these commands work as root user in the terminal?

```
cat /proc/cpuinfo | grep 'Revision' | awk '{print $3}'
cat /proc/device-tree/model
```

**Comment by dariuszzbyrad** [comment]
Could you please provide the result of the `ls -l /bin/sh` command? This will help us improve the functionality.

**Comment by byRizon** [comment]
yes those commands work as a root user

![1](https://github.com/user-attachments/assets/c6992fd7-7a8f-443c-bdb0-0479c67ffda7)

![2](https://github.com/user-attachments/assets/3e0da148-8e0a-4cf9-9311-f22e52ad3805)

**Comment by FDelporte** [comment]
@byRizon can you please try version 2.7.1-SNAPSHOT of Pi4J? @dariuszzbyrad improved the board detection process to prevent this error from happening.

You will probable need to add this to your pom:

```
<repositories>
    <repository>
        <id>oss-snapshots-repo</id>
        <name>Sonatype OSS Maven Repository</name>
        <url>https://oss.sonatype.org/content/groups/public</url>
        <releases>
            <enabled>false</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
```

**Comment by byRizon** [comment]
I've tested the 2.7.1-SNAPSHOT of Pi4J and some errors still occur. After some further testing and tinkering around i solved the issue.
Pi4J is able to read the board code, memory and the cpu revision with the 2.7.1-SNAPSHOT.
For some reason the root user didn't have access to the "jspawnhelper" file in the Java home. Thats why Pi4J was still unable to perform any commands via the ProcessBuilder in the CommandExecutor.

`chmod +x JAVA_HOME/lib/jspawnhelper` -> solved the issue for me.

**Comment by dariuszzbyrad** [comment]
Is this **exactly** the same error?
`
Could not execute cat /proc/cpuinfo | grep 'Revision' | awk '{print $3}' to detect the board model: IOException: Cannot run program "sh": error=13, Permission denied`

If so, it seems you're using an older version (prior to my fix). In the updated version, we no longer execute the above command. Instead, we directly read the `/proc/cpuinfo` file and perform the same transformation in Java.

**Comment by byRizon** [comment]
As is said before `Pi4J is able to read the board code, memory and the cpu revision with the 2.7.1-SNAPSHOT.`
ツ
