### ISSUE TITLE
Extend GitHub actions for automated publishing to oss.sonatype.org

### ISSUE THREAD

**Issue by FDelporte** [Pi4J/pi4j#55]
Up till now pushing new versions to Maven Repository has been a manual process, but to improve the release of new versions, it would be great to have this further automated.

Already done

- Libraries are available on https://oss.sonatype.org/#nexus-search;gav~com.pi4j~pi4j-core~~~~kw,versionexpand
- Maven publishing is already configured in pom.xml

To do (initial idea for further discussion)

- Add oss.sonatype.org commit keys to github project > settings > secrets > actions
- Define roles and restrict merge rights for feature, bug and release branches
- Further configure pom.xml, github action(s) and repository settings to have an automated way to publish 
   - each change in main branch = new snapshot push to oss.sonatype.org
   - when release branch gets merged = new release push to oss.sonatype.org

Inspiration can be found on 

* https://github.com/AlmasB/FXGL/blob/dev/.github/workflows/deploy_SNAPSHOT.yml
* https://github.com/actions/setup-java#publishing-using-apache-maven
* https://www.javacodegeeks.com/2020/07/how-to-publish-jar-to-maven-central.html
* https://github.com/raphw/byte-buddy/blob/master/.github/workflows/main.yml#L93

**Comment by savageautomate** [comment]
This item has been completed using the new "**Continuous Integration**" workflow action.

- https://github.com/Pi4J/pi4j-v2/actions/workflows/ci.yml
- https://github.com/Pi4J/pi4j-v2/blob/main/.github/workflows/ci.yml

The first step is to use Maven to **BUILD**, **TEST** and **DEPLOY** build SNAPSHOT artifacts to the OSS Nexus Maven Repository.
(https://oss.sonatype.org/content/repositories/snapshots/com/pi4j/)

If successful, the second step is to deploy (_add or update_) the build SNAPSHOT packages (*.DEB & *.ZIP) to the Pi4J APT/Download Repository (https://github.com/Pi4J/download) 

![image](https://user-images.githubusercontent.com/2251458/110671357-67b92400-819c-11eb-8519-8d0e766b8d02.png)

---

**Note:**  All build steps must succeed for this process to complete successfully.  This includes compiling native code, compiling Java code, JavaDoc, unit testing, packaging and deploying.
