### ISSUE TITLE
Some broken links in the README.md file of the JP4J-v2 project site https://github.com/Pi4J/pi4j-v2/tree/master

### ISSUE THREAD

**Issue by lburaggi** [Pi4J/pi4j#61]
A couple url links are broken and of course this is an obstacle for new-comer like me:

1. Pi4J V2 Documentation --> https://v2.pi4j.com/build
2. "Core code internals" on our website --> https://v2.pi4j.com/core-code-internals

Thank you for finding the time to fix them.

**Comment by FDelporte** [comment]
@lburaggi thanks for the heads up! Just this week we moved v2.pi4j.com to a GitHub pages site (sources in https://github.com/Pi4J/pi4j.github.io) and indeed these links were not reviewed yet. Should be all fixed now! Please share any unclarities as this helps us a lot to improve the documentation!
